"""add_order_to_columns

Revision ID: 72fdcc50eb06
Revises: 01b5c1db4aaa
Create Date: 2025-05-21 14:06:33.609794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fdcc50eb06'
down_revision: Union[str, None] = '01b5c1db4aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columns', 'order')
    # ### end Alembic commands ###
